### ISSUE TITLE
Why are there duplicate graphic modes in the settings?

### ISSUE THREAD

**Issue by chocolateimage** [divVerent/aaaaxy#124]
In this file:
https://github.com/divVerent/aaaaxy/blob/73946f97a3b3adc17fc4e4894f6007512cd7ef1b/internal/menu/settings.go#L93
You see "SVGA" and "8x8x4" is in the list 7 times
and at line 129, "Ukrainian" is "U" + "k" + "r" + "a" + "i" + "n" + "i" + "a" + "n"

why??? and can you fix this?

**Comment by divVerent** [comment]
That's an easter egg - the "fun" palettes can only be reached by hitting the right button seven times in a row. Kinda like how Android's Developer Mode works.

The substring at line 129 was hidden to not invite trolls too much, but I guess now that a localization file is in, there's no longer any point in that :)

**Comment by chocolateimage** [comment]
I didn't know that the "fun" palettes is an easter egg
