### ISSUE TITLE
Android F-Droid version failing to update

### ISSUE THREAD

**Issue by franz-ka** [divVerent/aaaaxy#185]
![Screenshot_20230302-152449_F-Droid](https://user-images.githubusercontent.com/803636/222519455-56694390-2dc6-44ed-9039-c72eccdd165f.png)
Hi i'm getting this error when trying to update the game from f-droid. I'm on android 8.1.0 Oreo. Thx!

**Comment by divVerent** [comment]
I just tried it out on one of my devices and it does not happen. I actually suspect a download error. F-Droid sadly keeps downloads cached for one day and thus reattempting won't fix it.

Does clearing F-Droid's cache fix it?

If not, does this work?

- Download https://f-droid.org/repo/io.github.divverent.aaaaxy_103030343.apk
- Connect with USB debugging
- Run: adb install io.github.divverent.aaaaxy_103030343.apk

If this doesn't work either, please provide adb logcat output or a bugreport.txt - thanks!

**Comment by divVerent** [comment]
I assume after me having published a new version, this should sure be fixed.
