### ISSUE TITLE
1.3.367 is unusably slow for me on Android

### ISSUE THREAD

**Issue by DamienCassou** [divVerent/aaaaxy#186]
While the 1.3.359 release on fdroid was perfect, updating to 1.3.367 made the game so slow that I can't play it anymore. I have an old phone (OnePlus 1) but it was working just perfect until the last release.

**Comment by petr666** [comment]
Confirming the same behavior (on Realme 7)

**Comment by divVerent** [comment]
1.3.367 contains a logging spam bug which may be causing this (even though I didn't notice a performance impact from it on my device) - can you retry with v1.3.372?

**Comment by DamienCassou** [comment]
I will do that but it is not on fdroid yet.

**Comment by divVerent** [comment]
Sounds good - will appear on F-Droid in the next few days. Always takes a
few days to get a build out.

**Comment by divVerent** [comment]
Can you confirm it is fixed now?

**Comment by DamienCassou** [comment]
Fdroid is still stuck at 1.3.367: https://f-droid.org/packages/io.github.divverent.aaaaxy/

**Comment by divVerent** [comment]
Ah, I see - F-Droid has some trouble with their build server. So it's just a matter of waiting for us.

**Comment by divVerent** [comment]
Hm... F-Droid now has built it but not released yet.

**Comment by divVerent** [comment]
F-Droid is still stuck. I have since released another version.

**Comment by DamienCassou** [comment]
fdroid now has 1.3.372 which works perfectly. This issue can be closed, thank you very much.

**Comment by divVerent** [comment]
Thanks for confirming!
