### ISSUE TITLE
Can't run on Chrome

### ISSUE THREAD

**Issue by Zyko0** [divVerent/aaaaxy#19]
I think my `localStorage` is broken on chrome, not sure why (even in private nav).
But maybe it should still start and show a warning (persistent or not) that the game can't be saved ? 😅 

![image](https://user-images.githubusercontent.com/13394516/158139318-c7441c85-7256-417b-befa-d85b5e4ee837.png)

Anyways, works fine on Edge ! (enjoying so far 🚀)

**Comment by divVerent** [comment]
It appears that the default of chrome://settings/cookies is changing from "Block third-party cookies in Incognito" to "Block third-party cookies". This probably breaks ALL games that have save states on Itch.

**Comment by Zyko0** [comment]
> It appears that the default of chrome://settings/cookies is changing from "Block third-party cookies in Incognito" to "Block third-party cookies". This probably breaks ALL games that have save states on Itch.

Makes sense!

I think I also failed to make it work before, it must have been for that reason

**Comment by divVerent** [comment]
04393e8f93885245e893c0570b6fef16d852052b now adds an exception handler for this condition.
