### ISSUE TITLE
scripts/version.sh doesn't have execute permissions

### ISSUE THREAD

**Issue by yurivict** [divVerent/aaaaxy#21]
It is run from another script but it doesn't have execute permissions so the build fails with Bourne shell.

**Comment by divVerent** [comment]
Does for me on a fresh clone:

```
[rpolzer@brlogenshfegle aaaaxy (git)-[main]-]$ ls -la scripts/version.sh  
-rwxr-xr-x 1 rpolzer rpolzer 4237 Apr  3 23:43 scripts/version.sh
```

Wonder where things went wrong? If I chmod -x it, git diff shows the diff too, showing that git is tracking this.

**Comment by yurivict** [comment]
It fetches tarballs from Go index servers:
```
=> v1.2.34.mod doesn't seem to exist in /disk-samsung/freebsd-ports/distfiles/go/games_aaaaxy/aaaaxy-v1.2.34.
=> Attempting to fetch https://proxy.golang.org/github.com/div!verent/aaaaxy/@v/v1.2.34.mod
v1.2.34.mod                                           3075  B   26 MBps    00s
=> v1.2.34.zip doesn't seem to exist in /disk-samsung/freebsd-ports/distfiles/go/games_aaaaxy/aaaaxy-v1.2.34.
=> Attempting to fetch https://proxy.golang.org/github.com/div!verent/aaaaxy/@v/v1.2.34.zip
v1.2.34.zip                                             24 MB   10 MBps    03s
```

It looks like they alter file permissions on Go servers: https://github.com/golang/go/issues/52999

**Comment by divVerent** [comment]
In this case, AAAAXY probably should always run shell scripts via "sh" and never via the executable bit.

I'll fix that.
