### ISSUE TITLE
Shepard Tone pitches aren't aligned with keyboard

### ISSUE THREAD

**Issue by yawnoc** [divVerent/aaaaxy#214]
In Shepard Tone, the sounded note pitches are 3 semitones lower than the expected keyboard pitch.

E.g. the note A (`shepard_00.ogg`) is sounded when the player triggers the note C on the keyboard.
It should be `shepard_03.ogg` that is sounded for the note C.

https://user-images.githubusercontent.com/48375680/232242014-570fc6c0-b134-4ec8-8d3c-453af17358fa.mp4

**Comment by divVerent** [comment]
You are probably right - that must be an oversight.

shepard_00.ogg is played by ShepardC, but indeed, by sox's documentation, 0 is a middle A.

I'm gonna fix it by updating the file references. Very good finding!

**Comment by divVerent** [comment]
This also means that the chord played is wrong too - I wanted a C major chord, but it actually became A major. For this I will have to update the data files.

**Comment by divVerent** [comment]
Also, now the chord sequence for open (ECED) is actually a C, G7, C sequence, and the other exit is truly based on D minor.
