### ISSUE TITLE
scripts/build-generated-assets.sh doesn't use GO_FLAGS

### ISSUE THREAD

**Issue by yurivict** [divVerent/aaaaxy#23]
GO_FLAGS should be suppliable by the user because it tells Go what homedir is, etc.

**Comment by divVerent** [comment]
Can you give an example on how they would be used and what you would expect
to happen, like, concrete flag values you would use?

The tricky part is that some stuff in there needs to run locally, not cross.

(Also, IIRC the Go call in there became optional and I now use a
pregenerated file, as the output differed across platforms and graphviz
versions too much - so making graphviz layout part of the build process
ended reproducaility and input compatibility across platforms)

**Comment by yurivict** [comment]
> Based on this I am assuming you are creating a FreeBSD port for this game - many thanks BTW! 

You are welcome!


> [...] there is no support for FreeBSD audio on Ebiten [...]

Ebiten is Linux-only. They should also support OSS or Jack or some other protocol.


------------------

The license issue is the main show-stopper.
