### ISSUE TITLE
Make a Russian translation please

### ISSUE THREAD

**Issue by Wjxfi** [divVerent/aaaaxy#233]
with the help of the world's best translator, DeepL. I won't do it myself

**Comment by divVerent** [comment]
Before accepting a patch with that, I will have to verify this does not go against any OFAC sanctions.

**Comment by divVerent** [comment]
Given the current situation, it seems unlikely to be wise to provide a translation in Russian now. If you follow the news, you should probably know why.

However, it is already possible to run the game with custom translation files - and if there is demand, I can make that way easier, as well.

**Comment by divVerent** [comment]
Make your people stop murdering my relatives, and we can talk. (And BTW I did not say people would have to do something with code - I did offer support to put a language file next to the game executable or something similar, very easy steps for anyone who needs them)

This discussion is closed.
