### ISSUE TITLE
Creating demo on android

### ISSUE THREAD

**Issue by noakodaren** [divVerent/aaaaxy#234]
It seams to be impossible to generate a demo file when playing on android. One way this could be possible is by putting demo files with the date and time in `/sdcard/Android/data/io.github.divVerent.aaaaxy/files/demos` if the user enables an option to do so. A better way would be to make this directory configurable.

As another related suggestion, it would be nice to be able to enable the timer in android.

These things would be useful for speedrunning on android without recording the screen.

Great game by the way!

**Comment by noakodaren** [comment]
I can confirm that this works, and it is really helpful!

Another downside is that the demo file has the same name every time you run the game, so the old one gets overwritten. This is not good if you accidentally restart the game when you want to save the demo. A possible solution would be to create an option that prepends the current date and time to the filename (like `demo_record_prepend_time`).

When I added `"show_time": "true"` to the config.json file, I got a timer. The problem is that the timer is on top of the controls where you have your thumb, so it is hard to actually read it. If you add "advanced settings" (I like that idea), it would be nice to be able to move around the timer like you can move the controls.
![Screenshot_20230621-180705_AAAAXY](https://github.com/divVerent/aaaaxy/assets/94870395/8e89f9bb-0fb9-45d9-831f-f2434451bcf8)

**Comment by divVerent** [comment]
I think as for the timer, I'll just quickly move it to the center and use
the left for GC stats - after all, controls can't be in the center anyway.

As for demo - that's actually another idea. What if I don't do an advanced
settings feature, but do the date in demo filename thing - then for now you
can do this already by editing the JSON file, and I can better integrate
this into the menu later?

**Comment by divVerent** [comment]
Just added a way for you to set:

"always_demo_record_with_timestamp":
"/sdcard/Android/data/io.github.divVerent.aaaaxy/files/demos/%Y%m%d%H%M%S.dem",

to the JSON file. Will think about menu integration later.

This flag doesn't start with demo_ so it stays in the config (the regular
demo_record I want to keep as a one-time thing that is not saved to
configs).
