### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by divVerent** [divVerent/aaaaxy#24]
This seems good:

https://pkg.go.dev/golang.org/x/text/message

For menu and game code strings, we can use p.Sprint() directly and the extractor should just work; for in-game stuff, however, we need to write a custom extractor that gets the translatable strings out of the .tmx file.

Seems very feasible though. Do need to figure out how to make it auto extractable from source; if this doesn't seem feasible, we may need a different approach. Support for a website like Transifex would be nice, although not required.

**Comment by darltrash** [comment]
is there any advancements in this? i would love to translate this game! :)

**Comment by divVerent** [comment]
Sadly not yet - finally got around to figuring a concept for a touch
controls editor, that goes first.

The big issue with translating is that we'd also have to somehow cover the
strings in the .tmx file; I still have no idea how to handle that. Any
ideas regarding that?

Am Mo., 5. Dez. 2022 um 19:24 Uhr schrieb Neil Wolfkid <
***@***.***>:

**Comment by divVerent** [comment]
Actually, looks like I'll have to go with gotext (and the xgotext utility) or go-gettext (with the go-xgettext utility).

Mainly because [x/text/message](https://pkg.go.dev/golang.org/x/text/message) doesn't appear to support any file format that Transifex can manage.

**Comment by divVerent** [comment]
As for strings in the .tmx file, I think I'll write a utility to convert strings in there to a gettext-ish file, too. Shouldn't be particularly hard, just some extra steps.

**Comment by divVerent** [comment]
Looks like gotext is out because git.deineagentur.com doesn't respond for me; go-gettext it is then.

**Comment by divVerent** [comment]
Let's go with this: https://github.com/leonelquinteros/gotext

It seems well maintained and has an extraction utility.

**Comment by divVerent** [comment]
Cool, xgettext already "supports" the tmx format (just had to write an its file for it).

As for the gotext module, it might not be possible to use it "properly" - I can't read the translations from files but from the game's VFS only - but it seems like its `.po` module is public and usable: https://pkg.go.dev/github.com/leonelquinteros/gotext#Po.Parse

And it _seems_ like the utility does detect these "direct" calls too. Sounds good then...

**Comment by divVerent** [comment]
One thing I likely can't support is changing language at runtime. Sad, kinda; I need to know the strings at load time to pregenerate some images. On Android I also can't self-restart no matter what.

For now I will ignore that issue.

**Comment by divVerent** [comment]
I added basic translation support now (uses gettext-format .po files, covers in-game map text fully but almost no other text yet), but not tested yet and am currently stuck trying to create an organization on Transifex. I might end up a different collaboration tool in the end.

**Comment by divVerent** [comment]
Menu and all hardcoded text now has German variant:

![20221210-220142](https://user-images.githubusercontent.com/251568/206884404-8f454955-e929-4e95-a85f-d0e5b5901fc4.png)

Will translate all other game text to German next week. To activate German, pass `-language de` to the game binary. Use `-language ""` to switch to untranslated texts. There is no menu for this yet - will do that once at least one language is complete.

**Comment by divVerent** [comment]
Oh, right now I was using `poedit` - have no online collaboration site yet that works well for this :( but Transifex will if I can create a new organization there somehow.

**Comment by divVerent** [comment]
BTW, I intend to generally use `ll` names only, except when the language differs significantly by country/region (`zh_Hant_TW`, `zh_Hans_CN` come to mind). In-game I plan to only store the name that matches an actually defined locale of the game in the flag, but autodetection from system locale is planned and will prefer the long name over the short name.

**Comment by divVerent** [comment]
Now have a 100% German translation, and system locale detection for it, so all I still need is a language menu.

**Comment by divVerent** [comment]
FYI: can translate here now: https://www.transifex.com/aaaaxy/aaaaxy
