### ISSUE TITLE
matrix-release workflow should be updated

### ISSUE THREAD

**Issue by imbev** [divVerent/aaaaxy#255]
The repository for the matrix-commit action is being transferred a second time, krazykirby99999/matrix-commit@v1 -> i10b/matrix-commit@v1 -> imbev/matrix-commit@v1 .

Github might not support "double" redirects, so I suggest updating the workflow.

**Comment by divVerent** [comment]
Thanks!

I should note though that the workflow currently doesn't work - I only want to run it on tag push, not on every commit, but it appears to not support that: https://github.com/divVerent/aaaaxy/actions/runs/6332290884/job/17198493189

Hadn't found time to fix that yet though.
