### ISSUE TITLE
Imcompatible with android 10?

### ISSUE THREAD

**Issue by philibeur** [divVerent/aaaaxy#27]
Hello i can't install on samsung a7 (2018) with android 10, why?

**Comment by divVerent** [comment]
Right now I am limiting the versions it can run on as a proxy for performance requirements - I plan to lower this over time.

**Comment by divVerent** [comment]
I think I'll indeed go one Android release down, as I implemented automatic graphics settings adjustment for improving fps.

**Comment by divVerent** [comment]
Fixed by 47399594d3b857fc020672cb952408ca5159170b
