### ISSUE TITLE
THIS GAME IS UNPLAYABLE THERE IS NO CASH SHOP

### ISSUE THREAD

**Issue by lnee94** [divVerent/aaaaxy#289]
When I get a game I expect a hole in my wallet they string me along with some filler I have to slog through to get to the micro transactions. Seeing game is free I though it would have micro transactions but no. To make up for this disapointment add a donation botton so I can get my fix.

**Comment by divVerent** [comment]
That is a good idea - right now the Konami code in this game gives you 30 lives (no idea what those are gonna be good for), it should give you a lootbox instead ;)

**Comment by divVerent** [comment]
Anyway, thanks for the comment. As for donation, I take no money, however I recommend you to donate to humanitarian causes. There are lots of wars going on, so I guess feel free to pick which victims need the help most.

Have a nice day!
