### ISSUE TITLE
Non-clipping walls taking out the trash

### ISSUE THREAD

**Issue by h4ckerle** [divVerent/aaaaxy#29]
It seems, under certain conditions, platforms can travel trough walls. This is not reproducible during normal gameplay, but it has happened to me multiple times.
![Screenshot_20220920_131835](https://user-images.githubusercontent.com/76652420/191244860-409f9b15-1666-4ab6-aae6-1735edeaea9c.png)
However, this also seems to happen when holding action key when joining the level, in which case the platforms noclip through the dividers which also breaks the level.

![Screenshot_20220920_132601](https://user-images.githubusercontent.com/76652420/191246188-fe429c01-324a-4ee4-9751-f1e72e43ab88.png)

I have aaaaxy 1.2.331-1 installed from AUR on Arch Linux with Kernel 5.19.8-zen1-1-zen and I run aaaaxy via xwayland 22.1.3-1.

**Comment by divVerent** [comment]
I think I understand why this happens - you can move the platforms before the dividers are loaded, as the dividers have not loaded yet. Can't tell if bug or feature... but nice finding. In this concrete room I think I'll see if there's a way to prevent this from happening.

A pragmatic solution would be overlapping the dividers with a platform-killer tile; then if you do get a platform through, it'll respawn right away. I'll think about it.

**Comment by divVerent** [comment]
Getting a platform through the red tiles at the left, however, should be harder... I'll see if I can repro that. The cause of that is not clear to me yet.

**Comment by divVerent** [comment]
I can only get a platform through the switchable tiles at the left by holding push and moving right to temporarily despawn it.

I guess that is acceptable. I did consider making platforms force-load everything around them, but that has its own kind of issues.

Usually, platforms brought into a bad place this way can be rather easily despawned and thus you can retry that section - is there any other place where this is particularly annoying? It might also allow for shortcutting Multi-Party Authorization, I think.

**Comment by divVerent** [comment]
I just got a better idea to solve this - I made objectclips (i.e. entities that block platforms) spawn one pixel earlier. It also works, but is more generic and won't require level changes everywhere.

You may still be able to get platforms inside solid walls in some few places; couldn't find a place to make that happen yet.
