### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by alxv-su** [divVerent/aaaaxy#293]
I want to translate this game to Russian. But someone has already requested to add this language to the project on [app.transifex.com](https://explore.transifex.com/aaaaxy/aaaaxy/). Can you please accept that request or reject it so I can make my request?

**Comment by divVerent** [comment]
I am sorry, but due ongoing issues affecting me personally, I cannot accept a Russian language translation for the time being.

If you want though, I can offer you that I could add an easy way for you to make a "language pack" that users can add to the game if desired. At least for the Linux and Windows versions, probably for macOS too, it would be rather easy for me to provide users the ability to simply place language files right next to the game executable and use those if available.

Right now there is also a minor amount of per-language customization that is required to make a language work (like which font to use), but I think I can easily move that into the language files too to better enable the possibility of externally provided language packs.

**Comment by divVerent** [comment]
As a simple preparation, I now factored all per-language settings of the game that normally require code changes to add a language into the .po files themselves. If you want, I can soon add code to the game to automatically detect a pair of game.po and level.po files in the game executable's directory, and use that instead of the builtin languages. Would that be acceptable to you?

**Comment by alxv-su** [comment]
> If you want, I can soon add code to the game to automatically detect a pair of game.po and level.po files

It would be great. I already made first version of translation, but only able to use it in cheat mode which doesn't allow to save progress.

**Comment by divVerent** [comment]
OK, I just made changes to the game engine so it accepts .po files placed next to the game executable when you pass the option `-language=.`. I will later make it autodetect existence of such files at startup.

**Comment by divVerent** [comment]
Finished language pack support - now if one is placed next to the game executable, it will be detected by the in-game menu.

This is as much as I'll support for now - enjoy!
