### ISSUE TITLE
Option to move on-screen controls?

### ISSUE THREAD

**Issue by adapt-L** [divVerent/aaaaxy#31]
I saw this on f-droid and it has been a lot of fun.

However, the platforming is a bit difficult. It would be more comfortable if the B button was closer to the A button. Perhaps there should be an option on mobile to allow the user to move the on-screen controls.

**Comment by adapt-L** [comment]
but good job, it reminds me of this other game I played with my friends a couple years ago: https://store.steampowered.com/app/286100/You_Have_to_Win_the_Game/ except less linear (you can explore the levels in different orders, for example) and with more puzzles.

**Comment by divVerent** [comment]
Thanks; I have not yet a good concept for an input editor but yeah, either this or multiple predefined layouts is probably what we will need here. In particular I can imagine people to swap left/right, move B up/down and resize the buttons in general.

Do note that the B button is actually much larger than it looks - intentionally so one can use it conveniently on multiple devices, and doesn't slip off the button easily.

Gotta try You Have to Win the Game - obviously strong VVVVVV influence graphically, but CGA this time, not C64 :)

**Comment by divVerent** [comment]
For now, a first attempt at improving this is moving the action button to cover the entire side of the screen - anything that isn't the jump button.

Because with the two ways I use of holding the phone, the jump button is usually well "aimed" by thumb or index finger, while I do occasionally slide off the action button with the index or middle finger, respectively.

**Comment by rszasz** [comment]
Is it possible to use gamepad inputs?

**Comment by divVerent** [comment]
That should technically work - it does work with an Xbox-compatible USB
gamepad I have.

Am Di., 8. Nov. 2022 um 21:58 Uhr schrieb rszasz ***@***.***>:

**Comment by divVerent** [comment]
I just added a primitive input editor. It's still a bit glitchy, primarily it right now just refuses to do any overlaps but doesn't help you be accurate - but it's usable and it should be impossible to create an unplayable layout with it.

![Screenshot_20221217-203608](https://user-images.githubusercontent.com/251568/208273601-7265c15f-67c9-45aa-ab0a-a773539f113c.png)

It's going to be in the next release which I'm likely gonna start making on Monday.
