### ISSUE TITLE
no content?

### ISSUE THREAD

**Issue by chriscamacho** [divVerent/aaaaxy#32]
Only seems to be one screen in the game with nothing else in reach, assuming there is at least one more screen then you need to moderate the level design to meet players half way. Current state of the game is unplayable to none mind readers....

**Comment by divVerent** [comment]
Where are you in the game? Like on which screen?

**Comment by divVerent** [comment]
In case you're on the very starting screen, Leap of Faith... look closely if anything happens near your feet. Then you will see how to progress.

**Comment by divVerent** [comment]
Closing due to no reply - feel free to reopen when you have additional information.
