### ISSUE TITLE
Score: 149.9999999999&NS

### ISSUE THREAD

**Issue by denilsonsa** [divVerent/aaaaxy#335]
I started playing this game about one year ago on my Steam Deck. I installed it using FlatHub.

Today, I decided to pick it up again (updated to the latest version from FlatHub). I noticed something strange:

![aaaaxy](https://github.com/divVerent/aaaaxy/assets/121676/8e65488c-46e4-45e2-8403-ad299d3e0784)

This score of `149.9999999999&NS` is probably unintended.

**Comment by divVerent** [comment]
No, that is very intended :)

A recent feature addition includes an additional factor in the score. It tells me:

- "149": You got 149 notes (that's the score).
- ".9999999999": You got all question/exclamation-mark blocks, including the hidden ones (that's hidden in the fractional part). (NOTE: I changed the full-amount score to be .9999999998 in a later change to remove the need to count nines, so it'll change to that for you too)
  - Yes, this looks a bit weird, and the newer change should make it a bit less weird. It becomes rather clear when you keep playing the game and see this number increase.
- "&": You got a 100% run done (i.e. all checkpoints and game won).
- "N": You got all notes.
- "S": You got all secrets.

One thing you lack right now is "all paths" - i.e. there are paths between two checkpoints that you haven't taken yet. The map should be highlighting them right now.

**Comment by denilsonsa** [comment]
Ooohhh… Intentional but obtuse/cryptic.

How about splitting it into multiple lines, so that it becomes very clear about their meaning? Something like:

    149/149 notes
    ??/?? blocks
    ??/?? paths

It can still have a short score useful for speedrun categories (e.g. 149.9%), but the amount of decimal digits makes it look like a floating point error. (Besides being just confusing to the end-user.)

Anyway, that's my simple suggestion. And if you decide not to implement it, I will still respect your game design decisions, even though I may disagree with them.

**Comment by divVerent** [comment]
Well, it's meant to look cryptic. Point taken about looking a bit too similar to a floating point math error. I'll think about it more.

The general idea was that question mark blocks in the game do nothing. And now - they still do nothing, but they increment your score. A bit. But never enough for a single point. You can hit as many as you want, they won't ever increase the score by one - they'll get close, but never actually reach it.

That's the message it is trying to convey.

But yeah - gonna think about it some more.

**Comment by denilsonsa** [comment]
I think part of the issue is that scores in video-games were more meaningful in the 1990s, and nowadays they are mostly ignored.

And the other part of the issue is the score being always hidden, except when the player opens the menu screen. Thus, the relationship between "actions" and "getting points" is lost. In old games, you could see the little number flying up, while also observing the score increasing in the HUD. But in aaaaxy there is no HUD and no visible score, so the game itself is communicating scores aren't that important.

Having something that gets you closer to incrementing one unit, but never quite reaching it, sounds like a fun clever idea. But it's not communicated well here. Maybe something worth revisiting in a different game that prominently displays the score. It also reminds me of [TeX](https://en.wikipedia.org/wiki/TeX#TeX82) version numbering, which gets closer and closer to π.

**Comment by divVerent** [comment]
Yeah, "the score is meaningless" is also a thing I kinda want to convey there as well.

Note that the only visible number is about the number of the notes read. These don't matter at all for the game (other than that there is a "speedrun category" for all notes). The question blocks OTOH - they don't even give coins. They just show that eight lines symbol that indicates that they produced - absolutely nothing (Super Mario Maker uses this to indicate that the block failed to spawn something because there are already too many objects of the given category).

For those blocks, the indicator right now uses an exponential function (as in, each block brings you about 46% closer to a full point), but I don't quite like how many digits that produces - so I may revisit it later.

**Comment by divVerent** [comment]
Moving to a new number sequence - quadratic instead of exponential:

```
2024/02/28 12:27:26.072389 [INFO] 0 -> 
2024/02/28 12:27:26.072412 [INFO] 1 -> .033
2024/02/28 12:27:26.072432 [INFO] 2 -> .065
2024/02/28 12:27:26.072449 [INFO] 3 -> .097
2024/02/28 12:27:26.072466 [INFO] 4 -> .128
2024/02/28 12:27:26.072484 [INFO] 5 -> .159
2024/02/28 12:27:26.072500 [INFO] 6 -> .189
2024/02/28 12:27:26.072517 [INFO] 7 -> .218
2024/02/28 12:27:26.072533 [INFO] 8 -> .247
2024/02/28 12:27:26.072549 [INFO] 9 -> .276
2024/02/28 12:27:26.072565 [INFO] 10 -> .304
2024/02/28 12:27:26.072582 [INFO] 11 -> .331
2024/02/28 12:27:26.072599 [INFO] 12 -> .358
2024/02/28 12:27:26.072614 [INFO] 13 -> .384
2024/02/28 12:27:26.072631 [INFO] 14 -> .410
2024/02/28 12:27:26.072657 [INFO] 15 -> .435
2024/02/28 12:27:26.072672 [INFO] 16 -> .459
2024/02/28 12:27:26.072689 [INFO] 17 -> .483
2024/02/28 12:27:26.072705 [INFO] 18 -> .507
2024/02/28 12:27:26.072722 [INFO] 19 -> .530
2024/02/28 12:27:26.072738 [INFO] 20 -> .552
2024/02/28 12:27:26.072753 [INFO] 21 -> .574
2024/02/28 12:27:26.072768 [INFO] 22 -> .595
2024/02/28 12:27:26.072787 [INFO] 23 -> .616
2024/02/28 12:27:26.072803 [INFO] 24 -> .636
2024/02/28 12:27:26.072819 [INFO] 25 -> .656
2024/02/28 12:27:26.072834 [INFO] 26 -> .675
2024/02/28 12:27:26.072852 [INFO] 27 -> .694
2024/02/28 12:27:26.072870 [INFO] 28 -> .712
2024/02/28 12:27:26.072887 [INFO] 29 -> .729
2024/02/28 12:27:26.072905 [INFO] 30 -> .746
2024/02/28 12:27:26.072923 [INFO] 31 -> .763
2024/02/28 12:27:26.072941 [INFO] 32 -> .778
2024/02/28 12:27:26.072960 [INFO] 33 -> .794
2024/02/28 12:27:26.072975 [INFO] 34 -> .808
2024/02/28 12:27:26.072988 [INFO] 35 -> .823
2024/02/28 12:27:26.073004 [INFO] 36 -> .836
2024/02/28 12:27:26.073020 [INFO] 37 -> .849
2024/02/28 12:27:26.073038 [INFO] 38 -> .862
2024/02/28 12:27:26.073054 [INFO] 39 -> .874
2024/02/28 12:27:26.073070 [INFO] 40 -> .885
2024/02/28 12:27:26.073081 [INFO] 41 -> .896
2024/02/28 12:27:26.073091 [INFO] 42 -> .906
2024/02/28 12:27:26.073101 [INFO] 43 -> .916
2024/02/28 12:27:26.073111 [INFO] 44 -> .925
2024/02/28 12:27:26.073125 [INFO] 45 -> .934
2024/02/28 12:27:26.073139 [INFO] 46 -> .942
2024/02/28 12:27:26.073153 [INFO] 47 -> .950
2024/02/28 12:27:26.073167 [INFO] 48 -> .957
2024/02/28 12:27:26.073187 [INFO] 49 -> .963
2024/02/28 12:27:26.073201 [INFO] 50 -> .969
2024/02/28 12:27:26.073217 [INFO] 51 -> .975
2024/02/28 12:27:26.073232 [INFO] 52 -> .979
2024/02/28 12:27:26.073247 [INFO] 53 -> .984
2024/02/28 12:27:26.073262 [INFO] 54 -> .988
2024/02/28 12:27:26.073278 [INFO] 55 -> .991
2024/02/28 12:27:26.073292 [INFO] 56 -> .993
2024/02/28 12:27:26.073307 [INFO] 57 -> .995
2024/02/28 12:27:26.073321 [INFO] 58 -> .997
2024/02/28 12:27:26.073332 [INFO] 59 -> .998
```

Has the same feeling but will look a lot less like a bug.
