### ISSUE TITLE
Add license for the game assets

### ISSUE THREAD

**Issue by rl2939** [divVerent/aaaaxy#403]
What is the license for the game assets (the sprites of your game)? I ask because the license for the assets tends to be different from the games code (which you have under the Apache license). 

It could be a Creative Commons license, be copyrighted for yourself, or something else.

**Comment by divVerent** [comment]
Assets by me (https://github.com/divVerent/aaaaxy/tree/main/assets) are under the same license as the rest of the game. Game assets by others (https://github.com/divVerent/aaaaxy/tree/main/third_party) are under their respective licenses, as described in that directory.

Yes, the player character is based on https://opengameart.org/content/classic-hero-and-baddies-pack - the modifications I made, inasmuch they are sufficiently complex to constitute copyright, are under the same license as the game itself, Apache 2.0.

**Comment by rl2939** [comment]
Hey,



Thanks for showing me where the game assets (and their licenses) are. 

> Yes, the player character is based on https://opengameart.org/content/classic-hero-and-baddies-pack - the modifications I made, inasmuch they are sufficiently complex to constitute copyright (about which I have seriously no idea), are under the same license as the game itself, Apache 2.0.

I noticed that the sprites for the player character are still [licensed under the Creative Commons Zero](https://github.com/divVerent/aaaaxy/blob/main/third_party/grafxkid_classic_hero_and_baddies_pack/LICENSE), not the Apache License. Did you mean to change this license to the Apache License?

**Comment by divVerent** [comment]
Both licenses apply - the original license to the original art and ideas,
and the Apache 2.0 license to my modifications, inasmuch they constitute
copyright.

Whether they do I can honestly not say. But my modifications are listed in
the COPYRIGHT.md files so you can make your own opinion on that - to me
this is a borderline case.
