### ISSUE TITLE
Translation: French

### ISSUE THREAD

**Issue by divVerent** [divVerent/aaaaxy#41]
Based on the current user base, French is a language worth adding to the game.

This can be done here:

https://transifex.com/aaaaxy/aaaaxy

As I do not speak French, I am filing this issue as an invitation to contribute.

**Comment by divVerent** [comment]
I prefilled with a machine translation. Someone please review and fix https://www.transifex.com/aaaaxy/aaaaxy/language/fr/ so it can be included!

Be aware that tags like `{{ExitButton}}` or `{{BR}}` need to remain unmodified. Transifex marked most of these issues but not all.

**Comment by ZubrowFR** [comment]
Hello, would have been happy to review this translation but there is an error 404 when I go on the website.

**Comment by divVerent** [comment]
The link works for me - I think one first needs to create a Transifex account before one can use it.

I also just created some tests for translations - the game will at startup log errors about mismatched format strings or {{Placeholders}}, and also list most oversized texts (most but not all text is covered; main non-covered stuff is the menu and some text with {{Placeholders}}).

**Comment by divVerent** [comment]
Just improved the automatic verification, and fixed all the format string errors in the French translation on Transifex.

Still need to check game output for oversized text and need to either insert line breaks ({{BR}}) - ideally that'd be a translator's job, as I usually put them at a good point for the phrasing - or make text boxes wider (in many places that is possible).

**Comment by divVerent** [comment]
In particular, if you're at the point where you think it's basically complete, and just texts are too wide for their boxes - you may just hand it to me there and I should be able to fix most or all of them without rewording. I believe I have enough basic French knowledge to do that part myself.

**Comment by divVerent** [comment]
FYI I since expanded many text boxes to accommodate Portuguese, and documented reordering support for format strings (use `%[1]s`, `%[2]s` etc. placeholders if needed).

**Comment by divVerent** [comment]
Should I remove the machine translations again from Transifex?

**Comment by NoEnd-yt** [comment]
> Based on the current user base, French is a language worth adding to the game.
> 
> This can be done here:
> 
> [transifex.com/aaaaxy/aaaaxy](https://transifex.com/aaaaxy/aaaaxy)
> 
> As I do not speak French, I am filing this issue as an invitation to contribute.

I'll be glad to help as I speak French :)

**Comment by divVerent** [comment]
Thank you! I just approved.

**Comment by NoEnd-yt** [comment]
There are just some strings that I find unclear because I don't have the context and have never seen them, for example "All Flipped". I know how I need to translate it but it could be more precise if I had context.

**Comment by divVerent** [comment]
That is a speedrun category, similar to Any%, 100%, All Exits, etc. (means that you finish the game with all checkpoints in the flipped/mirrored state).

**Comment by divVerent** [comment]
Also answered this via translator notes on Transifex now: https://github.com/divVerent/aaaaxy/commit/11a93f39f890b4da849a2ad65ca606e57eab9d3a

**Comment by divVerent** [comment]
Tracked on Transifex.
