### ISSUE TITLE
Translation: Spanish

### ISSUE THREAD

**Issue by divVerent** [divVerent/aaaaxy#42]
Based on the current user base, Spanish is a language worth adding to the game.

This can be done here:

https://transifex.com/aaaaxy/aaaaxy

As I do not speak Spanish, I am filing this issue as an invitation to contribute.

**Comment by divVerent** [comment]
I prefilled with a machine translation. Someone please review and fix https://www.transifex.com/aaaaxy/aaaaxy/language/fr/ so it can be included!

Be aware that tags like `{{ExitButton}}` or `{{BR}}` need to remain unmodified. Transifex marked most of these issues but not all.

**Comment by darltrash** [comment]
I do speak spanish, and I am willing to translate this game.

**Comment by divVerent** [comment]
Thanks!

Looks like one has to sign in or sign up on https://www.transifex.com/aaaaxy/aaaaxy/ first, regarding the link. Apparently the deep link only works when already signed in.

**Comment by divVerent** [comment]
FYI I since expanded many text boxes to accommodate Portuguese, and documented reordering support for format strings (use `%[1]s`, `%[2]s` etc. placeholders if needed).

**Comment by divVerent** [comment]
Should I remove the machine translations again from Transifex?

**Comment by oraliahdz** [comment]
I can help with Spanish. I have already sent my request via transiges

**Comment by divVerent** [comment]
I see you requested Spanish (Mexico) - for now I added you to generic Spanish, however do feel free to use Mexican variants consistently. From what I have heard (but please correct me if I am wrong), Mexican Spanish is still well understood by people from Spain - especially if written down - so it makes sense to use your variant as a fallback and we can always rearrange later if someone wants to make Spain Spanish specifically (also, if the differences are minor, we can even just use the templating system to replace a few words while using the same translation file - see the Portuguese translation that does this). This is needed as the locale system will never use an `es_MX` translation for an `es_SP` or `es_UY` user, but will use an es translation for any user. If this is OK for you, please translate in the `es` language in Transifex, and I will then document that we prefer Mexican variety of Spanish in this language for now but may split up later (I then have to figure out which variant should be the "default" one that countries without an explicit translation get, given there being so many countries that speak varieties of Spanish).

You also requested English (Mexico) - I can certainly add that too, but can you explain what would be some differences you would be making? Also, if we do that, please explicitly copy over strings to be left as is using Transifex's copy button, so I can gauge how complete it is.

Thank you!

**Comment by oraliahdz** [comment]
In the game.pot, does Fernando de Noronha refers to the person or to the place?

**Comment by divVerent** [comment]
It refers to the place, and is used in the contexts "Welcome to ..." and
"... Road Rage".

I think the Transifex developer notes field should say that, but I am going
to verify - I may have missed this one.

**Comment by oraliahdz** [comment]
game.pot file completed

**Comment by divVerent** [comment]
Thanks! Looking good so far. I marked all strings but one as reviewed after performing technical review, BTW :)

**Comment by divVerent** [comment]
Tracked on Transifex.
